### PR TITLE
Guard against NaN

### LINKED ISSUE #17: Crash: RangeError [ERR_OUT_OF_RANGE]
Got this crash report from Manyverse, so it means async-append-only-log version 3.0.1

App: se.manyver 0.2101.5-beta-googlePlay (95)
Device: Xiaomi Redmi Note 4 (arm64-v8a | armeabi-v7a | armeabi)
OS: Android 9 (SDK 28)
User comment: the app just crashed

```
The value of \\\"offset\\\" is out of range. It must be an integer. Received NaN
RangeError [ERR_OUT_OF_RANGE]: The value of \\\"offset\\\" is out of range. It must be an integer. Received NaN
    at boundsError (internal/buffer.js:75:11)
    at Buffer.readUInt16LE (internal/buffer.js:238:5)
    at getData (/data/data/se.manyver/files/nodejs-project/index.js:63060:25)
    at /data/data/se.manyver/files/nodejs-project/index.js:63075:7
    at Request._callback (/data/data/se.manyver/files/nodejs-project/index.js:63054:9)
    at Request.Trwq+KqeWzxsbUet+Omb+wC9uH2QMBcZNBUiXOCqCv4=.Request.callback (/data/data/se.manyver/files/nodejs-project/index.js:44790:8)
    at onread (/data/data/se.manyver/files/nodejs-project/index.js:75871:31)
    at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5)
```

Manually interpreting the modules in the stack trace:

```
The value of \\\"offset\\\" is out of range. It must be an integer. Received NaN
RangeError [ERR_OUT_OF_RANGE]: The value of \\\"offset\\\" is out of range. It must be an integer. Received NaN
    at boundsError (internal/buffer.js:75:11)
    at Buffer.readUInt16LE (internal/buffer.js:238:5)
    at getData (async-append-only-log)
    at get (async-append-only-log)
    at Request._callback (raf.read callback in async-append-only-log)
    at Request.prototype.callback (random-access-storage)
    at RandomAccessFile.prototype._read callback onread (random-access-file)
    at FSReqCallback.wrapper [as oncomplete] (fs.js:520:5)
```

----

Update: And same crash for an entirely different user.

App: se.manyver 0.2101.5-beta-googlePlay (95)
Device: Google Pixel 3a (arm64-v8a | armeabi-v7a | armeabi)
OS: Android 11 (SDK 30)
User comment: N/A

----

And another

App: se.manyver 0.2101.5-beta-googlePlay (95)
Device: Google Pixel 5 (arm64-v8a | armeabi-v7a | armeabi)
OS: Android 11 (SDK 30)
User comment: crashes on startup every time

### PR DESCRIPTION
**Pull request by arj03**
This should fix #17

### CODE REVIEW

**Review by staltz — APPROVED** [review]
Decent fix, we just need to make sure that such errors are handled in ssb-db2 somehow so that it doesn't keep on bubbling up until it produces a crash. We shouldn't be getting NaNs to begin with.

**Comment by arj03** [comment]
True. But at least this error should be easier to understand I think.

**Comment by staltz** [comment]
About the recent commit, I'd actually have that as a separate error. -1 is indicative "initialized but empty", while NaN is indicative of "we messed up with the programming somewhere".

**Comment by arj03** [comment]
@staltz better?

**Review by staltz — APPROVED** [review]
Happy

**Pull request merged**
