### PR TITLE
use push.collect instead of our own

### PR DESCRIPTION
**Pull request by staltz**
I'm actually working on #48, but I sometimes stumble upon refactors, so I'm branching them off early instead of accumulating them with the compaction PR.

### CODE REVIEW

**Review by arj03 — APPROVED** [review]
👍

**Comment by arj03** [comment]
Whoops, didn't see the tests fail

**Comment by staltz** [comment]
Yeah, I'm working on it. It's just a few tests were using collect() in a funky way, so gotta rewrite them

**Comment by staltz** [comment]
See commit https://github.com/ssb-ngi-pointer/async-append-only-log/pull/49/commits/3e448bf91afd95fd32dabd0f26d3ec433c0ea433, it actually simplifies the tests a bit.

The CI is still failing, but on a different spot. I'll work on that now too

**Review by arj03 — APPROVED** [review]
Good cleanup :)

**Pull request merged**
