### PR TITLE
Move function that does not use closure scope to be private member

### PR DESCRIPTION
**Pull request by Barbarrosa**
The resume callback doesn't require closure scope, and I found using [0x](https://www.npmjs.com/package/0x) that moving this function reduces its time on the top of the stack while running JITDB benchmarks.

### CODE REVIEW

**Comment by arj03** [comment]
I ran the jitdb benchmark using this and couldn't see a difference. I also ran the flamegraphs and they were about the same. Having names does help both while benchmarking and while getting stacktraces so in that regard this is a win and one should not discount the importance of that. Thanks!

**Comment by Barbarrosa** [comment]
@arj03 I've been successively running the benchmarks after incorporating other outstanding changes, so that may partly explain why our results differ. You can see push-stream/push-stream#7 and pull-stream/pull-stream#130 for other changes that may improve JITDB performance.

**Comment by arj03** [comment]
Ohh nice. Word of caution Dominic is not really doing js anymore so we have to get those PRs reviewed and fixed another way.

**Comment by Barbarrosa** [comment]
@arj03 Looks like there are other members in the pull-stream Github organization, so I tagged them for that PR. Do you have any suggestions about what to do for push-stream? There *may* be private group members, but I'm betting against it & wouldn't know how to contact them.

**Comment by staltz** [comment]
> Do you have any suggestions about what to do for push-stream? There _may_ be private group members, but I'm betting against it & wouldn't know how to contact them.

We need to gently ask Dominic to add us as maintainers. He probably won't object to it, but it's a stretch to ask him because he spends his days building boats.

**Comment by Barbarrosa** [comment]
@staltz I messaged Dominic regarding the PRs, but I think you or @arj03 should probably be the ones asking to be maintainers since you've known Dominic longer.

**Comment by Barbarrosa** [comment]
@arj03 @staltz Dominic messaged me back saying he's willing to give you access if you ask him (and he named both of you without me prompting).

**Pull request merged**
